// The Phase 0 results table (docs/audit/compat-results.md) from the v1 adapter's results, and the
// wattage comparison between v1 and the plan's formula ("Κατανάλωση και τροφοδοτικό").

import { gpuPsu } from '../../src/lib/builder';
import type { GpuListing } from '../../src/types';
import type { Scenario, ScenarioPart } from './scenario';
import { V1_CHECKS, modelOf, type ScenarioResult } from './v1-adapter';

// ---------- The plan's power formula ----------

/**
 * Reference power figures for the parts used in the wattage scenarios: graphics card total board power
 * and CPU package power limit (AMD PPT / Intel PL2). Recalled from the makers' published specs — NOT
 * fetched in Phase 0 (no requests to maker sites). Phase 2 must source the real tables.
 */
export const REFERENCE_WATTS: Record<string, number> = {
  'RTX 5070': 250,
  'RTX 5070 Ti': 300,
  'RTX 5080': 360,
  'RTX 5090': 575,
  'RX 9070 XT': 304,
  'Ryzen 5 7600': 88,
  'Ryzen 7 9700X': 88,
  'Ryzen 7 9800X3D': 162,
  'Ryzen 9 9950X': 230,
  'Core i7-14700K': 253,
  'Core i9-14900K': 253,
};

const n = (p: ScenarioPart | undefined, f: string) => Number(p?.fields[f] ?? 0);

/** The plan's estimate: per-part figures, sum × 1.3 rounded up to 50 W, at least the card maker's figure. */
export function planWatts(s: Scenario): { sum: number; byFormula: number; cardMaker: number | null; recommended: number; missing: string[] } {
  const of = (c: string) => s.parts.filter((p) => p.category === c);
  const missing: string[] = [];
  const ref = (name: string) => {
    if (!(name in REFERENCE_WATTS)) missing.push(name);
    return REFERENCE_WATTS[name] ?? 0;
  };
  const gpu = of('gpu')[0];
  const cpu = of('cpu')[0];
  const sticks = of('ram').reduce((t, p) => t + n(p, 'modules') * p.quantity, 0);
  const drives = of('storage').reduce((t, p) => t + p.quantity, 0);
  const fans = of('fan').reduce((t, p) => t + n(p, 'pack') * p.quantity, 0);
  const pump = of('cooler').some((p) => p.fields.type === 'AIO') ? 5 : 0;
  const sum = (gpu ? ref(String(gpu.fields.chip)) : 0) + (cpu ? ref(cpu.name) : 0) + 50 + 5 * sticks + 8 * drives + 3 * fans + pump;
  const byFormula = Math.ceil((sum * 1.3) / 50) * 50;
  const cardMaker = gpu ? gpuPsu(modelOf(gpu).cheapest as GpuListing) : null;
  return { sum, byFormula, cardMaker, recommended: Math.max(byFormula, cardMaker ?? 0), missing };
}

// ---------- Markdown ----------

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
const VERDICT = { correct: 'correct', wrong: '**wrong**', gap: 'v1 does not check this' } as const;

export function report(scenarios: Scenario[], results: ScenarioResult[]): string {
  const byId = new Map(scenarios.map((s) => [s.id, s]));
  const lines: string[] = [];
  const push = (...l: string[]) => lines.push(...l);
  const rules = results.flatMap((r) => r.rules.map((x) => ({ ...x, id: r.id })));
  const count = <T extends string>(xs: T[]) => xs.reduce<Record<string, number>>((o, x) => ({ ...o, [x]: (o[x] ?? 0) + 1 }), {});
  const sv = count(results.map((r) => r.verdict));
  const rv = count(rules.map((r) => r.verdict));

  push(
    '# Compatibility scenarios: v1 results',
    '',
    'Generated by `npm test` (tests/compat/v1-report.test.ts) from the scenario files in tests/compat/scenarios/',
    'through the v1 adapter (tests/compat/v1-adapter.ts), which calls the same functions the v1 builder UI uses.',
    'Do not edit by hand; `npx vitest run -u` rewrites it after an intended change.',
    '',
    '## Totals',
    '',
    `- Scenarios: ${results.length} — correct ${sv.correct ?? 0}, wrong ${sv.wrong ?? 0}, not checked by v1 ${sv['not checked by v1'] ?? 0}.`,
    '  (A scenario is "wrong" if any of its expected rules is wrong; "correct" if at least one rule is correct and the rest are not checked by v1.)',
    `- Expected rule results: ${rules.length} — correct ${rv.correct ?? 0}, wrong ${rv.wrong ?? 0}, not checked by v1 ${rv.gap ?? 0}.`,
    '',
    '## How v1 answers are mapped to the plan’s levels',
    '',
    '| v1 says | Plan level |',
    '|---|---|',
    '| check "Fits" (Χωράει) | pass |',
    '| check "Likely fits" (Πιθανότατα χωράει), an estimate | note |',
    '| check "Fit not verified" (Χωρίς επιβεβαίωση), data missing | note |',
    '| check "Incompatible" (Ασύμβατο), part hidden by "Only compatible" | error |',
    '| summary note with the warning icon (level "error") | error (v1 has no warning level) |',
    '| summary note with the info icon | note; the advice "the CPU comes with a cooler" counts as pass |',
    '',
    'Verdicts: **correct** = same level; **wrong** = v1 checks the rule and answers differently; **v1 does not check this** =',
    'v1 has no such check, cannot hold the scenario’s quantities (it has one part per category), the expected result depends',
    'on a field v1 does not have, or the plan’s margin band (rules 6, 8, 14: a warning just inside the limit) does not exist in v1.',
    '',
    '## Rules v1 checks',
    '',
    '| Rule | v1 check | Scenarios (expected level → verdict) |',
    '|---|---|---|',
  );
  for (let rule = 1; rule <= 26; rule++) {
    const rs = rules.filter((r) => r.rule === rule);
    const list = rs.map((r) => `${r.id} ${r.expected}→${r.verdict === 'gap' ? 'not checked' : r.verdict}`).join(', ') || '—';
    push(`| ${rule} | ${V1_CHECKS[rule] ?? 'none'} | ${list} |`);
  }
  push('', '## Results', '', '| Scenario | Expected | What v1 reports | Verdict |', '|---|---|---|---|');
  for (const r of results) {
    const s = byId.get(r.id)!;
    const exp = r.rules.map((x) => `R${x.rule} ${x.expected}`).join('<br>');
    const says = r.rules.map((x) => `R${x.rule}: ${cell(x.v1Says)}`).join('<br>');
    const ver = r.rules.map((x) => `R${x.rule} ${VERDICT[x.verdict]}${x.detail ? ` (${cell(x.detail)})` : ''}`).join('<br>');
    const title = `**${r.id}** ${cell(s.title)}${s.planExample ? ' *(plan example)*' : ''}${r.ui.unexpressed.length ? `<br>v1 cannot hold: ${cell(r.ui.unexpressed.join('; '))}` : ''}`;
    push(`| ${title} | ${exp} | ${says} | ${ver} |`);
  }
  push(
    '',
    '## What the v1 UI shows for each scenario build',
    '',
    'Per part: the label the part gets against the rest of the build (`rate`), and the summary notes (`buildNotes`, "Pick a …" lines left out).',
    '',
  );
  for (const r of results) {
    const parts = r.ui.parts.map((p) => `${p.category} "${cell(p.name)}": ${p.label}${p.reasons.length ? ` — ${cell(p.reasons.join(' '))}` : ''}`);
    const notes = r.ui.notes.map((x) => `[${x.level}] ${cell(x.text)}`);
    const st = r.ui.status;
    push(
      `- **${r.id}** — status: ${st.fits} fit, ${st.likely} likely, ${st.unverified} not verified, ${st.no} incompatible; recommended PSU: ${r.ui.requiredWatts ?? '—'} W`,
      ...parts.map((p) => `  - ${p}`),
      ...notes.map((x) => `  - note ${x}`),
    );
  }
  push(
    '',
    '## Recommended power supply: v1 vs the plan formula',
    '',
    'v1 (`requiredWatts`): the card’s stated minimum PSU (product page) or the chip maker’s table, else 350 W without a card,',
    '+100 W for Ryzen 9 / Core i9 / Core Ultra 9. Plan: (card TBP + CPU PPT/PL2 + 50 W board + 5 W per stick + 8 W per drive',
    '+ 3 W per fan + 5 W AIO pump) × 1.3, rounded up to the next 50 W, and at least the card maker’s figure.',
    'TBP/PPT/PL2 figures are reference values recalled from the makers’ specs (not fetched in Phase 0; see REFERENCE_WATTS).',
    '',
    '| Scenario | Build | v1 recommends | Plan sum | Plan × 1.3 → 50 W | Card maker | Plan recommends | Difference (plan − v1) |',
    '|---|---|---|---|---|---|---|---|',
  );
  for (const id of ['S12', 'S25', 'S59', 'S62', 'S63', 'S64']) {
    const s = byId.get(id);
    const r = results.find((x) => x.id === id);
    if (!s || !r) continue;
    const w = planWatts(s);
    const build = s.parts.filter((p) => ['cpu', 'gpu', 'ram', 'storage', 'fan', 'psu'].includes(p.category)).map((p) => `${p.quantity > 1 ? `${p.quantity}× ` : ''}${p.name}`).join(' + ');
    push(
      `| ${id} | ${cell(build)} | ${r.ui.requiredWatts ?? '—'} W | ${w.sum} W | ${w.byFormula} W | ${w.cardMaker ?? '—'} W | ${w.recommended} W | ${w.recommended - (r.ui.requiredWatts ?? 0)} W${w.missing.length ? ` (no reference for ${w.missing.join(', ')})` : ''} |`,
    );
  }
  push('');
  return lines.join('\n');
}
