// Text of the component catalogue itself (headings, captions); the components' own text is in
// src/ui/strings.ts.
export const P = {
  pageTitle: { el: 'Κατάλογος components', en: 'Component catalogue' },
  intro: {
    el: 'Φάση 1, στάση 2: τρία λογότυπα, δύο παλέτες και κάθε component σε κάθε κατάσταση, με πραγματικά προϊόντα και τιμές από τα σημερινά δεδομένα. Μόνο σε development.',
    en: 'Phase 1, stop 2: three logos, two palettes and every component in every state, with real products and prices from today\'s data. Development builds only.',
  },
  logo: { el: 'Λογότυπο', en: 'Logo' },
  palette: { el: 'Παλέτα', en: 'Palette' },
  theme: { el: 'Θέμα', en: 'Theme' },
  language: { el: 'Γλώσσα', en: 'Language' },
  blue: { el: 'Μπλε', en: 'Blue' },
  indigo: 'Indigo',
  light: { el: 'Φωτεινό', en: 'Light' },
  dark: { el: 'Σκούρο', en: 'Dark' },
  loadingData: { el: 'Φόρτωση σημερινών δεδομένων…', en: 'Loading today\'s data…' },
  sections: { el: 'Ενότητες', en: 'Sections' },

  // Identity
  sLogos: { el: 'Λογότυπα', en: 'Logos' },
  logosIntro: {
    el: 'Ένα χρώμα, χωρίς gradients, SVG. Κάθε κατεύθυνση σε φωτεινό και σκούρο φόντο, στα 16, 32 και 48 px, στην κεφαλίδα, ως favicon καρτέλας και ως εικόνα κοινοποίησης (1200 × 630). Το επιλεγμένο λογότυπο οδηγεί την κεφαλίδα και το favicon αυτής της σελίδας.',
    en: 'One colour, no gradients, SVG. Each direction on light and dark backgrounds, at 16, 32 and 48 px, in the header, as a browser-tab favicon and as a social image (1200 × 630). The selected logo drives this page\'s header and favicon.',
  },
  logoA: { el: 'Α. Blueprint', en: 'A. Blueprint' },
  logoAText: { el: 'Γωνίες τεχνικού σχεδίου γύρω από ένα chip, και το όνομα δίπλα.', en: 'Technical-drawing corner marks around a chip, the name beside it.' },
  logoB: { el: 'Β. Monogram', en: 'B. Monogram' },
  logoBText: { el: '«BD» σαν ίχνη πλακέτας, κομμένο από στρογγυλεμένο τετράγωνο.', en: '"BD" drawn like circuit traces, cut out of a rounded square.' },
  logoC: { el: 'Γ. Wordmark', en: 'C. Wordmark' },
  logoCText: {
    el: 'Μόνο το όνομα: «Build» έντονο, «Draft» λεπτό, chip στη θέση της τελείας. Για favicon: το B με την τελεία-chip.',
    en: 'The name only: "Build" bold, "Draft" light, a chip for the dot. Favicon: the B with the chip dot.',
  },
  onLight: { el: 'Σε φωτεινό', en: 'On light' },
  onDark: { el: 'Σε σκούρο', en: 'On dark' },
  onBrand: { el: 'Σε brand', en: 'On brand' },
  inBrand: { el: 'Σε χρώμα brand', en: 'In brand colour' },
  sizes: { el: 'Μεγέθη', en: 'Sizes' },
  tab: { el: 'Favicon σε καρτέλα', en: 'Favicon in a tab' },
  social: { el: 'Εικόνα κοινοποίησης 1200 × 630 (σε σμίκρυνση)', en: 'Social image 1200 × 630 (scaled down)' },
  socialTagline: { el: 'Τιμές εξαρτημάτων PC στην Ελλάδα · PC Builder', en: 'PC part prices in Greece · PC Builder' },
  socialFacts: { el: '5 πηγές τιμών · 9 κατηγορίες · ενημέρωση κάθε 6 ώρες', en: '5 price sources · 9 categories · updated every 6 hours' },
  inHeader: { el: 'Στην κεφαλίδα, σε πραγματικό μέγεθος', en: 'In the header, at real size' },

  sColours: { el: 'Χρώματα', en: 'Colours' },
  coloursIntro: {
    el: 'Το brand δεν είναι πράσινο: πράσινο, πορτοκαλί, κόκκινο και γαλάζιο σημαίνουν μόνο συμβατότητα και τιμή. Ο πίνακας αντίθεσης υπολογίζεται ζωντανά από τα tokens, για την τρέχουσα παλέτα και τα δύο θέματα.',
    en: 'The brand is not green: green, orange, red and light blue only mean compatibility and price. The contrast table is computed live from the tokens, for the current palette and both themes.',
  },
  brandScale: { el: 'Κλίμακα brand', en: 'Brand scale' },
  neutralScale: { el: 'Ουδέτερα', en: 'Neutrals' },
  meaning: { el: 'Χρώματα με σημασία', en: 'Meaning colours' },
  mSuccess: { el: 'Πράσινο: συμβατό, πτώση τιμής, «Χωράει»', en: 'Green: compatible, price drop, "Fits"' },
  mWarning: { el: 'Πορτοκαλί: προειδοποίηση, θέλει ενέργεια από εσένα', en: 'Orange: warning, needs action from you' },
  mDanger: { el: 'Κόκκινο: σφάλμα, άνοδος τιμής, «Δεν χωράει»', en: 'Red: error, price rise, "Doesn\'t fit"' },
  mInfo: { el: 'Γαλάζιο: σημείωση, «Πιθανότατα χωράει», «Δεν επιβεβαιώθηκε»', en: 'Light blue: note, "Likely fits", "Not verified"' },
  hueGap: { el: 'Απόσταση απόχρωσης brand ↔ γαλάζιο σημείωσης', en: 'Hue distance brand ↔ note light blue' },
  contrast: { el: 'Αντίθεση WCAG (AA: 4,5 για κείμενο, 3 για εικονίδια και πλαίσια πεδίων)', en: 'WCAG contrast (AA: 4.5 text, 3 icons and field borders)' },
  pair: { el: 'Ζεύγος', en: 'Pair' },
  use: { el: 'Χρήση', en: 'Use' },
  need: { el: 'Ελάχιστο', en: 'Needs' },
  pass: { el: 'περνά', en: 'pass' },
  fail: { el: 'αποτυγχάνει', en: 'fails' },

  sType: { el: 'Τυπογραφία και κίνηση', en: 'Type and motion' },
  typeIntro: {
    el: 'Inter για όλο το UI με αριθμούς ίδιου πλάτους σε τιμές και specs· JetBrains Mono μόνο για κωδικούς. Έξι μεγέθη. Κίνηση μόνο σε transform και opacity· με «λιγότερη κίνηση» όλα γίνονται αμέσως.',
    en: 'Inter for the whole UI with tabular figures in prices and specs; JetBrains Mono for codes only. Six sizes. Motion only on transform and opacity; with "reduce motion" everything is instant.',
  },
  sample: { el: 'Κάρτες γραφικών από 189,90 € — RTX 5070 12GB', en: 'Graphics cards from €189.90 — RTX 5070 12GB' },
  codes: { el: 'Κωδικοί', en: 'Codes' },
  motion: { el: 'Κίνηση', en: 'Motion' },
  play: { el: 'Αναπαραγωγή', en: 'Play' },

  // Components
  sButtons: { el: 'Κουμπιά', en: 'Buttons' },
  stDefault: { el: 'Κανονικό', en: 'Default' },
  stHover: 'Hover',
  stFocus: { el: 'Εστίαση', en: 'Focus' },
  stActive: { el: 'Πατημένο', en: 'Active' },
  stDisabled: { el: 'Ανενεργό', en: 'Disabled' },
  stLoading: { el: 'Φόρτωση', en: 'Loading' },
  vPrimary: { el: 'Κύριο', en: 'Primary' },
  vSecondary: { el: 'Δευτερεύον', en: 'Secondary' },
  vGhost: 'Ghost',
  vDanger: { el: 'Κίνδυνος', en: 'Danger' },
  btnPrimary: { el: 'Προσθήκη', en: 'Add' },
  btnSecondary: { el: 'Λεπτομέρειες', en: 'Details' },
  btnGhost: { el: 'Αντιγραφή', en: 'Copy' },
  btnDanger: { el: 'Καθαρισμός', en: 'Clear' },
  smallAndIcon: { el: 'Μικρό και μόνο εικονίδιο', en: 'Small and icon-only' },

  sChips: { el: 'Chips φίλτρων', en: 'Filter chips' },
  chipsIntro: {
    el: 'Επιλογή = πατημένο (με ✓). Με 0 αποτελέσματα: ανενεργό, εκτός αν είναι ήδη επιλεγμένο. Τα ενεργά φίλτρα πάνω από τη λίστα κυλούν οριζόντια στο κινητό· το «×» τα αφαιρεί.',
    en: 'Selected = pressed (with ✓). With 0 results: disabled, unless already selected. Applied filters above the list scroll sideways on phones; "×" removes them.',
  },
  applied: { el: 'Ενεργά φίλτρα', en: 'Applied filters' },
  upTo900: { el: 'Έως 900 €', en: 'Up to €900' },
  saleOnly: { el: 'Μόνο προσφορές', en: 'On sale only' },

  sCompat: { el: 'Συμβατότητα', en: 'Compatibility' },
  compatIntro: {
    el: 'Χρώμα, εικονίδιο και λέξη μαζί, ώστε να διαβάζεται και χωρίς χρώμα. Ο λόγος φαίνεται πάντα ως κείμενο. Τα μηνύματα είναι παραδείγματα· οι κανόνες έρχονται στη Φάση 2.',
    en: 'Colour, icon and word together, so it reads without colour too. The reason is always visible text. The messages are examples; the rules come in Phase 2.',
  },
  rError: { el: 'Η μητρική είναι ATX· το κουτί δέχεται έως Micro ATX.', en: 'The board is ATX; the case takes up to Micro ATX.' },
  rWarning: { el: 'Η κάρτα (325 mm) χωράει, αλλά απέχει λιγότερο από 10 mm από το όριο του κουτιού (330 mm).', en: 'The card (325 mm) fits, but is less than 10 mm from the case limit (330 mm).' },
  rLikely: { el: 'Εκτίμηση: κάρτες αυτού του chip είναι έως 305 mm· το κουτί δέχεται 360 mm.', en: 'Estimate: cards with this chip are up to 305 mm; the case takes 360 mm.' },
  rUnverified: { el: 'Το ύψος της ψύκτρας δεν αναφέρεται από καμία πηγή.', en: 'No source states the cooler\'s height.' },
  rPass: { el: 'Socket AM5 και στα δύο.', en: 'AM5 socket on both.' },
  rFan: { el: 'Εκτίμηση: το κουτί έχει 6 θέσεις ανεμιστήρα· τα μεγέθη τους δεν αναφέρονται.', en: 'Estimate: the case has 6 fan positions; their sizes are not stated.' },
  rFits: { el: 'Ύψος ψύκτρας 155 mm· το κουτί δέχεται 170 mm.', en: 'Cooler height 155 mm; the case takes 170 mm.' },

  sPrice: { el: 'Κελί τιμής', en: 'Price cell' },
  priceIntro: {
    el: 'Τιμή, πραγματικό κατάστημα και πηγή, μεταφορικά όταν είναι γνωστά, διαθεσιμότητα όταν είναι γνωστή, πότε ελέγχθηκε και αλλαγή 7 ημερών με ετικέτα. Όλα ορατά, τίποτα μόνο σε hover.',
    en: 'Price, the real shop and the source, shipping when known, availability when known, when it was checked and a labelled 7-day change. All visible, nothing hover-only.',
  },
  pKnown: { el: 'Όλα γνωστά', en: 'Everything known' },
  pKnownNote: { el: 'Η διαθεσιμότητα είναι δείγμα: συλλέγεται από τη Φάση 2.', en: 'Availability is a sample: collected from Phase 2.' },
  pNoShipping: { el: 'Μεταφορικά άγνωστα', en: 'Shipping unknown' },
  pNoAvail: { el: 'Διαθεσιμότητα άγνωστη', en: 'Availability unknown' },
  pStale: { el: 'Παλαιότερη από 24 ώρες', en: 'Older than 24 hours' },
  pUnusual: { el: 'Ασυνήθιστα χαμηλή', en: 'Unusually low' },
  pNone: { el: 'Δεν υπάρχει σήμερα στα δεδομένα.', en: 'Not in today\'s data.' },
  pSample: { el: 'δείγμα', en: 'sample' },

  sSpecs: { el: 'Γραμμή specs', en: 'Spec line' },
  specsIntro: {
    el: 'Τα 3–5 πιο σημαντικά χαρακτηριστικά κάθε κατηγορίας, πάντα με την ίδια σειρά· ό,τι δεν είναι γνωστό κρατά τη θέση του ως «—». Ένα πραγματικό μοντέλο ανά κατηγορία.',
    en: 'The 3–5 specs that matter in each category, always in the same order; anything unknown keeps its place as "—". One real model per category.',
  },

  sFilters: { el: 'Ομάδες φίλτρων', en: 'Filter groups' },
  filtersIntro: {
    el: 'Λίστα επιλογών με μετρητές («Περισσότερα» μετά τις 8, αναζήτηση από τις 15), εύρος με slider και πεδία, διακόπτης, και η γραμμή κάλυψης. Πραγματικοί αριθμοί από τις κάρτες γραφικών και τους δίσκους.',
    en: 'Checkbox list with counts ("Show more" after 8, search from 15), range with slider and inputs, switch, and the coverage line. Real numbers from graphics cards and storage.',
  },
  gpuMakers: { el: 'Κατασκευαστής κάρτας', en: 'Card maker' },
  storageMakers: { el: 'Κατασκευαστής δίσκου', en: 'Drive maker' },
  priceRange: { el: 'Τιμή', en: 'Price' },
  lengthField: { el: 'Μήκος', en: 'Length' },
  switchOff: { el: 'Ανενεργός', en: 'Off' },
  switchDisabled: { el: 'Μόνο ιστορικά χαμηλά (καμία σήμερα)', en: 'All-time lows only (none today)' },
  tooltipText: { el: 'Από τα καταστήματα και τους κατασκευαστές.', en: 'From the shops and the makers.' },

  sLists: { el: 'Πίνακας, κάρτες, part list', en: 'Table, cards, part list' },
  listsIntro: {
    el: 'Επικεφαλίδες που ταξινομούν· γραμμή σε κανονική, hover, εστίαση και επιλεγμένη κατάσταση· η ίδια πληροφορία ως κάρτα για κινητό· οι γραμμές του PC Builder.',
    en: 'Sorting headers; a row as default, hover, focus and selected; the same information as a phone card; the PC Builder\'s rows.',
  },
  cards: { el: 'Κάρτες (κινητό)', en: 'Cards (phones)' },
  partList: { el: 'Part list (PC Builder)', en: 'Part list (PC Builder)' },
  partStates: { el: 'Κενή θέση και προϊόν που δεν πωλείται πλέον', en: 'Empty slot and a product no longer sold' },

  sPaging: { el: 'Σελιδοποίηση', en: 'Pagination' },
  sOverlays: { el: 'Sheet, διάλογος, toast, tooltip', en: 'Sheet, dialog, toast, tooltip' },
  overlaysIntro: {
    el: 'Στατικά για να φαίνονται, και κουμπιά που τα ανοίγουν ζωντανά. Το tooltip είναι μόνο για επιπλέον λεπτομέρειες.',
    en: 'Static so they can be seen, and buttons that open them live. The tooltip is for extra details only.',
  },
  openSheet: { el: 'Άνοιγμα sheet', en: 'Open sheet' },
  openDialog: { el: 'Άνοιγμα διαλόγου', en: 'Open dialog' },
  showToast: { el: 'Εμφάνιση toast', en: 'Show toast' },
  filtersTitle: { el: 'Φίλτρα', en: 'Filters' },
  showModels: (n: number) => ({ el: `Εμφάνιση ${n} μοντέλων`, en: `Show ${n} models` }),
  dialogTitle: { el: 'Καθαρισμός build;', en: 'Clear the build?' },
  dialogText: { el: 'Θα αφαιρεθούν και τα 8 εξαρτήματα. Μπορείτε να το αναιρέσετε αμέσως μετά.', en: 'All 8 parts will be removed. You can undo it right after.' },
  clear: { el: 'Καθαρισμός', en: 'Clear' },
  toastCopied: { el: 'Η λίστα αντιγράφηκε.', en: 'List copied.' },
  toastCleared: { el: 'Το build καθαρίστηκε.', en: 'Build cleared.' },
  toastGo: { el: 'Θα άνοιγε', en: 'Would open' },

  sStates: { el: 'Κενό, φόρτωση, σφάλμα, 404', en: 'Empty, loading, error, 404' },
  skeletonTable: { el: 'Φόρτωση (πίνακας)', en: 'Loading (table)' },
  skeletonCards: { el: 'Φόρτωση (κινητό)', en: 'Loading (phone)' },

  sNav: { el: 'Διαδρομή, κατάσταση πηγών, αναζήτηση', en: 'Breadcrumbs, source status, search' },
  navIntro: {
    el: 'Η γραμμή κατάστασης λέει «πηγές» (όχι «καταστήματα») και δείχνει πότε ενημερώθηκε η καθεμία· όσες είναι παλαιότερες από 24 ώρες σημειώνονται. Η αναζήτηση είναι ζωντανή, με τα σημερινά μοντέλα.',
    en: 'The status line says "sources" (not "shops") and shows when each one updated; any older than 24 hours is marked. Search is live, with today\'s models.',
  },
  statusCategory: { el: 'Σε σελίδα κατηγορίας (Δίσκοι)', en: 'On a category page (Storage)' },
  statusSite: { el: 'Σε όλο το site (footer)', en: 'Site-wide (footer)' },
  searchLive: { el: 'Ζωντανά: γράψτε π.χ. «rtx 50», «990 pro», «corsair», «μητρικές»', en: 'Live: type e.g. "rtx 50", "990 pro", "corsair", "motherboards"' },
  searchOpen: { el: 'Ανοιχτή, με «rtx 50»', en: 'Open, with "rtx 50"' },

  sShell: { el: 'Κέλυφος: κεφαλίδα, μενού, πλακίδια, footer', en: 'Shell: header, menu, tiles, footer' },
  shellIntro: {
    el: 'Η κεφαλίδα με το επιλεγμένο λογότυπο, το μενού «Εξαρτήματα» ανοιχτό, και σε πλαίσια 360 px: κινητό, η σελίδα πλακιδίων /parts, η αναζήτηση, το sheet φίλτρων και το part list.',
    en: 'The header with the selected logo, the "Parts" menu open, and in 360 px frames: phone, the /parts tiles page, search, the filter sheet and the part list.',
  },
  menuOpen: { el: 'Με ανοιχτό μενού', en: 'With the menu open' },
  phone: { el: 'Κινητό 360 px', en: 'Phone 360 px' },
  fShell: { el: 'Σελίδα κατηγορίας', en: 'Category page' },
  fParts: { el: 'Εξαρτήματα (/parts)', en: 'Parts (/parts)' },
  fSearch: { el: 'Αναζήτηση', en: 'Search' },
  fSheet: { el: 'Sheet φίλτρων', en: 'Filter sheet' },
  fBuilder: { el: 'Part list', en: 'Part list' },
} as const;
